server:
  port: 8081
spring:
  application:
    name: lightingRouting
  resources:
    static-locations: file:D:\workspace\spider_workspace\spider-manager\web\dist
  mvc:
    static-path-pattern:/**
  cloud:
    gateway:
      routes:
        - id: test01
          uri: https://cn.bing.com
          predicates:
            - Path=/xxx/**               #断言，路径匹配 注意：Path 中 P 为大写
            - Method=GET
          filters:
            - StripPrefix=1

